print('hello')
print('What is your name?')
myname = input()
print('This is dood t meet you ')
print('The lengh of your name is:')
print(len(myname))
print('What is your age?')
myAge = input()
print('You will be ' + str(int(myAge) + 1) + 'in a year.')
